// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aberaTech.Fitness.Data;

#nullable disable

namespace aberaTech.Fitness.Data.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    [Migration("20260830223025_AthleteHistory")]
    partial class AthleteHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("aberaTech.Fitness.Data.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageHr")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("MaxHr")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Instant>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.AthleteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<double>("HomeAltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("LtSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("PastPeakDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("PastPeakSeconds")
                        .HasColumnType("double precision");

                    b.Property<int?>("PastPeakYear")
                        .HasColumnType("integer");

                    b.Property<double>("PlanMinutesPerWeek")
                        .HasColumnType("double precision");

                    b.Property<int>("ReferenceHr")
                        .HasColumnType("integer");

                    b.Property<double>("StartVdot")
                        .HasColumnType("double precision");

                    b.Property<LocalDate?>("VdotMeasuredOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.BodyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BodyFatPercent")
                        .HasColumnType("double precision");

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("BodyMetrics");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<LocalDate>("TargetDate")
                        .HasColumnType("date");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Metric")
                        .IsUnique();

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.StrengthSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("StrengthSets");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.StrengthSet", b =>
                {
                    b.HasOne("aberaTech.Fitness.Data.Activity", null)
                        .WithMany("Sets")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.Activity", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
