// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aberaTech.Fitness.Data;

#nullable disable

namespace aberaTech.Fitness.Data.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    partial class FitnessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("aberaTech.Fitness.Data.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageHr")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("Indoor")
                        .HasColumnType("boolean");

                    b.Property<double?>("LoadKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHr")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Instant>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.AftResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<double>("DeadliftKg")
                        .HasColumnType("double precision");

                    b.Property<int>("HandReleasePushUps")
                        .HasColumnType("integer");

                    b.Property<double>("PlankSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("SprintDragCarrySeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("TwoMileSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("AftResults");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.AthleteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvailableHoursPerWeek")
                        .HasColumnType("double precision");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<bool?>("Female")
                        .HasColumnType("boolean");

                    b.Property<double?>("GoalWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("HomeAltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("LtHr")
                        .HasColumnType("integer");

                    b.Property<double?>("LtSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("PastPeakDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("PastPeakSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("PastPeakWeightKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("PastPeakYear")
                        .HasColumnType("integer");

                    b.Property<double>("PlanMinutesPerWeek")
                        .HasColumnType("double precision");

                    b.Property<int>("ReferenceHr")
                        .HasColumnType("integer");

                    b.Property<LocalDate?>("SelectionDate")
                        .HasColumnType("date");

                    b.Property<double>("StartVdot")
                        .HasColumnType("double precision");

                    b.Property<double?>("SustainedWeeklyHours")
                        .HasColumnType("double precision");

                    b.Property<LocalDate?>("VdotMeasuredOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.BodyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BodyFatPercent")
                        .HasColumnType("double precision");

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("BodyMetrics");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<LocalDate>("TargetDate")
                        .HasColumnType("date");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Metric")
                        .IsUnique();

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.Lap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageHr")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<double>("Seconds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.LockedPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("ActualSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("Compliance")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<LocalDate>("MadeOn")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("PredictedFastSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("PredictedSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("PredictedSlowSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("RaceMassKg")
                        .HasColumnType("double precision");

                    b.Property<LocalDate>("TargetDate")
                        .HasColumnType("date");

                    b.Property<double>("WeeklyHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TargetDate");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.OwnerDocument", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.StravaConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("AthleteId")
                        .HasColumnType("bigint");

                    b.Property<Instant>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StravaConnections");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.StrengthSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("StrengthSets");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.SyncState", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastOutcome")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Source");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.Lap", b =>
                {
                    b.HasOne("aberaTech.Fitness.Data.Activity", null)
                        .WithMany("Laps")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.StrengthSet", b =>
                {
                    b.HasOne("aberaTech.Fitness.Data.Activity", null)
                        .WithMany("Sets")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aberaTech.Fitness.Data.Activity", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
