// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aberaTech.Scheduling.Data;

#nullable disable

namespace aberaTech.Scheduling.Data.Migrations;

[DbContext(typeof(SchedulingDbContext))]
[Migration("20261001170705_PhoneAlarmSettings")]
partial class _20261001170705_PhoneAlarmSettings
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(id);

                b.Property<string>("FriendlyName")
                    .HasColumnType("text");

                b.Property<string>("Xml")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("DataProtectionKeys");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertAcknowledgementRecord", b =>
            {
                b.Property<string>("OccurrenceKey")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Instant>("AcknowledgedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Via")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)");

                b.HasKey("OccurrenceKey");

                b.ToTable("AlertAcknowledgements");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertCreatedEventRecord", b =>
            {
                b.Property<string>("EventId")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Instant>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("Critical")
                    .HasColumnType("boolean");

                b.Property<Instant>("EndsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("LeadMinutes")
                    .HasColumnType("integer");

                b.Property<string>("Location")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Instant>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("EventId");

                b.ToTable("AlertCreatedEvents");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertDeliveryRecord", b =>
            {
                b.Property<string>("OccurrenceKey")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Instant>("ClaimedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant?>("CompletedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Outcome")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("Receipt")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<Instant>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("OccurrenceKey");

                b.HasIndex("ClaimedAt");

                b.ToTable("AlertDeliveries");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertDeviceRecord", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("ApnsEnvironment")
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<string>("ApnsToken")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Instant>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant?>("LastSeenAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(60)
                    .HasColumnType("character varying(60)");

                b.Property<Instant?>("PushedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long>("PushedVersion")
                    .HasColumnType("bigint");

                b.Property<byte[]>("TokenHash")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.HasKey("Id");

                b.HasIndex("TokenHash")
                    .IsUnique();

                b.ToTable("AlertDevices");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertEventChangeRecord", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<Instant?>("AlertAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("Critical")
                    .HasColumnType("boolean");

                b.Property<bool>("Deleted")
                    .HasColumnType("boolean");

                b.Property<int?>("DurationMinutes")
                    .HasColumnType("integer");

                b.Property<Instant?>("EndsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("EventId")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<int?>("LeadMinutes")
                    .HasColumnType("integer");

                b.Property<string>("Location")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<bool>("LocationSet")
                    .HasColumnType("boolean");

                b.Property<Instant>("OriginalStartsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PickedLocation")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<bool>("Recurring")
                    .HasColumnType("boolean");

                b.Property<bool>("Reminder")
                    .HasColumnType("boolean");

                b.Property<bool>("Series")
                    .HasColumnType("boolean");

                b.Property<Instant?>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("TimeZone")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("Title")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");

                b.ToTable("AlertEventChanges");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertEventTypeRecord", b =>
            {
                b.Property<string>("EventId")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Instant>("LastSeenAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)");

                b.Property<Instant>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("EventId");

                b.HasIndex("LastSeenAt");

                b.ToTable("AlertEventTypes");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertMuteRecord", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer");

                b.Property<Instant?>("MutedUntil")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("AlertMutes");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertPushStateRecord", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer");

                b.Property<byte[]>("AlarmsFingerprint")
                    .HasColumnType("bytea");

                b.Property<Instant>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long>("Version")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("AlertPushStates");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertRoutineRecord", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<Instant>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<short[]>("Days")
                    .IsRequired()
                    .HasColumnType("smallint[]");

                b.Property<bool>("Enabled")
                    .HasColumnType("boolean");

                b.Property<short>("Hour")
                    .HasColumnType("smallint");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasMaxLength(60)
                    .HasColumnType("character varying(60)");

                b.Property<short>("Minute")
                    .HasColumnType("smallint");

                b.Property<short>("SnoozeMinutes")
                    .HasColumnType("smallint");

                b.Property<Instant>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("AlertRoutines");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertSettingsRecord", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer");

                b.Property<int>("BackupDelaySeconds")
                    .HasColumnType("integer");

                b.Property<int>("DefaultLeadMinutes")
                    .HasColumnType("integer");

                b.Property<string>("DefaultType")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasDefaultValue("none");

                b.Property<bool>("IncludeAllDay")
                    .HasColumnType("boolean");

                b.Property<int>("LookaheadHours")
                    .HasColumnType("integer");

                b.Property<int>("NotificationPriority")
                    .HasColumnType("integer");

                b.Property<string>("NotificationSound")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string[]>("OwnerEmails")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.Property<int>("PhoneSnoozeMinutes")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(9);

                b.Property<string>("PhoneSound")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasDefaultValue("default");

                b.Property<int>("PollMinutes")
                    .HasColumnType("integer");

                b.Property<int>("RepeatSeconds")
                    .HasColumnType("integer");

                b.Property<string>("Sound")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<int>("StopAfterMinutes")
                    .HasColumnType("integer");

                b.Property<string>("TimeZone")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<Instant>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("AlertSettings");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Alerts.AlertSkipRecord", b =>
            {
                b.Property<string>("OccurrenceKey")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Instant>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("OccurrenceKey");

                b.ToTable("AlertSkips");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.AdminSessionVersion", b =>
            {
                b.Property<string>("Email")
                    .HasMaxLength(320)
                    .HasColumnType("character varying(320)");

                b.Property<int>("Version")
                    .HasColumnType("integer");

                b.HasKey("Email");

                b.ToTable("AdminSessions");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.Appointment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("BookedZoneId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<bool>("Cancelled")
                    .HasColumnType("boolean");

                b.Property<string>("ConsentDisclosure")
                    .HasColumnType("text");

                b.Property<Instant?>("ConsentedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<string>("Email")
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)");

                b.Property<Instant>("EndsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("GoogleEventId")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)");

                b.Property<string>("PhoneE164")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)");

                b.Property<bool>("SmsConsent")
                    .HasColumnType("boolean");

                b.Property<Instant>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("StartsAt", "EndsAt");

                b.ToTable("Appointments");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.AvailabilityRuleRecord", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<bool>("Active")
                    .HasColumnType("boolean");

                b.Property<int>("Day")
                    .HasColumnType("integer");

                b.Property<LocalTime>("EndsAt")
                    .HasColumnType("time");

                b.Property<LocalTime>("StartsAt")
                    .HasColumnType("time");

                b.Property<string>("ZoneId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.HasKey("Id");

                b.ToTable("AvailabilityRules");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.HostCalendarCredential", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CalendarId")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("character varying(320)");

                b.Property<Instant>("ConnectedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ConnectedEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("character varying(320)");

                b.Property<string>("GrantedScopes")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)");

                b.Property<string>("ProtectedRefreshToken")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("HostCalendarCredentials");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.QueueEntryRecord", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ConsentDisclosure")
                    .HasColumnType("text");

                b.Property<Instant?>("ConsentedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<Duration>("Expected")
                    .HasColumnType("interval");

                b.Property<bool>("ImminentSent")
                    .HasColumnType("boolean");

                b.Property<Instant>("JoinedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant?>("LastAnnouncedStart")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PhoneE164")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)");

                b.Property<int>("Position")
                    .HasColumnType("integer");

                b.Property<Guid>("SessionId")
                    .HasColumnType("uuid");

                b.Property<bool>("SmsConsent")
                    .HasColumnType("boolean");

                b.Property<Instant?>("StartedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("State")
                    .HasColumnType("integer");

                b.Property<bool>("TurnSent")
                    .HasColumnType("boolean");

                b.Property<string>("ZoneId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("SessionId", "Position")
                    .IsUnique();

                b.HasIndex("SessionId", "State");

                b.ToTable("QueueEntries");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.QueueSession", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Instant>("ClosesAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Duration>("DefaultDuration")
                    .HasColumnType("interval");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<bool>("Open")
                    .HasColumnType("boolean");

                b.Property<Instant>("OpensAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("QueueSessions");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.SmsOptOut", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Instant>("OptedOutAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PhoneE164")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");

                b.HasIndex("PhoneE164")
                    .IsUnique();

                b.ToTable("SmsOptOuts");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Outbox.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid?>("AppointmentId")
                    .HasColumnType("uuid");

                b.Property<int>("Attempts")
                    .HasColumnType("integer");

                b.Property<string>("Body")
                    .IsRequired()
                    .HasMaxLength(1600)
                    .HasColumnType("character varying(1600)");

                b.Property<Instant>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Instant?>("DeliveredAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("IdempotencyKey")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<int>("Kind")
                    .HasColumnType("integer");

                b.Property<string>("LastError")
                    .HasColumnType("text");

                b.Property<Instant?>("NextAttemptAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ProviderMessageId")
                    .HasColumnType("text");

                b.Property<Guid?>("QueueEntryId")
                    .HasColumnType("uuid");

                b.Property<Instant?>("SentAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("State")
                    .HasColumnType("integer");

                b.Property<string>("ToPhoneE164")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)");

                b.HasKey("Id");

                b.HasIndex("IdempotencyKey")
                    .IsUnique();

                b.HasIndex("NextAttemptAt")
                    .HasFilter("\"NextAttemptAt\" IS NOT NULL");

                b.HasIndex("ProviderMessageId")
                    .IsUnique()
                    .HasFilter("\"ProviderMessageId\" IS NOT NULL");

                b.ToTable("Outbox");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.QueueEntryRecord", b =>
            {
                b.HasOne("aberaTech.Scheduling.Data.QueueSession", "Session")
                    .WithMany("Entries")
                    .HasForeignKey("SessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Session");
            });

        modelBuilder.Entity("aberaTech.Scheduling.Data.QueueSession", b =>
            {
                b.Navigation("Entries");
            });
#pragma warning restore 612, 618
    }
}
