// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aberaTech.Scheduling.Data;

#nullable disable

namespace aberaTech.Scheduling.Data.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260823231504_SmsConsent")]
    partial class SmsConsent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Data.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookedZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Instant>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("SmsConsent")
                        .HasColumnType("boolean");

                    b.Property<Instant>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StartsAt", "EndsAt");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Data.AvailabilityRuleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<LocalTime>("EndsAt")
                        .HasColumnType("time");

                    b.Property<LocalTime>("StartsAt")
                        .HasColumnType("time");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("AvailabilityRules");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Data.HostCalendarCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Instant>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ProtectedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HostCalendarCredentials");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Data.QueueEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Duration>("Expected")
                        .HasColumnType("interval");

                    b.Property<bool>("ImminentSent")
                        .HasColumnType("boolean");

                    b.Property<Instant>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LastAnnouncedStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SmsConsent")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<bool>("TurnSent")
                        .HasColumnType("boolean");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Position")
                        .IsUnique();

                    b.HasIndex("SessionId", "State");

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Data.QueueSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("ClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Duration>("DefaultDuration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.Property<Instant>("OpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("QueueSessions");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Instant?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<Guid?>("QueueEntryId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("ToPhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("NextAttemptAt")
                        .HasFilter("\"NextAttemptAt\" IS NOT NULL");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique()
                        .HasFilter("\"ProviderMessageId\" IS NOT NULL");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Data.QueueEntryRecord", b =>
                {
                    b.HasOne("aberaTech.Scheduling.Data.QueueSession", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("aberaTech.Scheduling.Data.QueueSession", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
