name: Trigger auto deployment for aberatechserver-app-202412211749

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/aberatechserver-app-202412211749-AutoDeployTrigger-b2da1de8-1ba7-4207-82c0-26222cd2e507.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ABERATECHSERVERAPP202412211749_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ABERATECHSERVERAPP202412211749_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ABERATECHSERVERAPP202412211749_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}aberaTech.Server
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: aberatechserver20241221175455.azurecr.io
          registryUsername: ${{ secrets.ABERATECHSERVERAPP202412211749_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ABERATECHSERVERAPP202412211749_REGISTRY_PASSWORD }}
          containerAppName: aberatechserver-app-202412211749
          resourceGroup: aberatechserver-app-202412211749ResourceGroup
          imageToBuild: aberatechserver20241221175455.azurecr.io/aberatechserver-app-202412211749:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


